title: Probability as a Service
description: "A parking space for my notes, thoughts, and projects"
author:
  name: "Andrew Repp"
  email: "Andrew@andrewrepp.com"
  url: "https://www.andrewrepp.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
# paginate: 5
# paginate_path: /page/:num/

# adding custom support for categories (or trying)
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  # - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Andrew Repp"
year : "2020"
