title: Systems as a Service
description: "A parking space for my notes, thoughts, and projects"
author:
  name: "Andrew Repp"
  email: "andrew@andrewrepp.com"
  url: "https://www.andrewrepp.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title

# adding custom support for categories (or trying)
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

# Custom variables
owner : "Andrew Repp"
year : "2023"
